---
title: "Travel tips and recommendations"
description: "@ Seoul, South Korea"
date: "2025-07-07"
toc: false
---

## General tips

- **IMPORTANT**: Summer in Korea is very hot and humid! When planning outdoor activities make sure you check out the weather beforehand. Fortunately, most buildings in Korea have ACs so try to stay indoor a lot during the summer.

- In general, “information friction” seems to be quite low in South Korea. That being said, be aware that popular places that you search for on the internet will be quite crowded. Do expect some queue lines and make sure you consider the tradeoff of visiting a nice place and spending lot of time in the queue (But also take into account that most good places will have large volume of people on average. So you will need to wait in most places you want to visit).

- **Maps**: Like many other East Asia countries, lot of systems in Korea are country-specific (unfortunately). If you tend to travel in Korea, I strongly recommend you download either “Naver map” or “Kakao map” on your phone. They are the google map equivalent app in Seoul. Note that google map will not work very well in Korea.

- **Transportation card**: Unfortunately, you cannot use your regular credit cards to pay for the public transportation. You will have to buy some pre-paid card. For short-term trips, you can buy them at the station. I recommend you try out [Climate card](https://chillandtravel.com/climate-card-seoul-guide/) which is a relatively new pre-paid pass card that came out in Seoul. Also, remember to **TAP IN and TAP OUT** on both buses and subways!

- **Ordering in restaurant**: In Korea, there is no tip culture. That being said, no servers are assigned to your table (like in US). So do not passively wait for them to come get your order. In Korea, you can just call the server by raising your hand and calling out “excuse me”. This is not considered impolite and you will see that many people do that. Otherwise, they are not going to periodically check on you. Also, unlike other countries, you don’t pay the bill in your table. When you are done eating, just go to the counter and pay for the meal.

- **Public safety**: I would say Seoul is one of the most safe cities in the world(in terms of traveling). You don’t need to worry too much about where you are going (within Seoul, it will be very unlikely that you stumble into some dangerous regions) and you can walk around at night. Many people will just walk around Seoul at 2, 3am and it would be fine. 

- **Drinking**: One nice thing about Korea’s drinking culture is that you can drink your bottle outside. I would suggest you take some night-time picnic to Hangang river with some drinks. There are lot of parks near the river where you will see people drinking and enjoying the view.

- **Bicycle**: Seoul also has [public bicycle system](https://www.bikeseoul.com:457/main.do?lang=en). I didn’t try it often but I heard it’s pretty good. But warning: Unlike US or European countries, there are not many lanes strictly designated to bicycle in Korea. Also, it is bit rare for bicycle to go on the same road with the cars. In fact, it will be more common to just ride the bicycle in the pedestrian way. So when traveling in bicycle, just use the pedestrian way and be careful of the people. You should also keep an eye on the street for bicycle as you walk.

## Transportation tips

- **Airport to Seoul (bus)**: There are few ways to go from Incheon international airport to Seoul. Easiest way (but little bit more expensive) is airport bus (a.k.a. limousine bus). You can buy the ticket in the airport and they cover most major places in Seoul. You can also use the subway although I have never tried it.

- **Transportation within Seoul (bus and subway)**: If you stay in Seoul, you will be able to access most (to be honest, all) locations in the city using public transportation. Main transportation is “bus” and “subway.” Another advantage of Seoul is that bus and subway system are very well interconnected. You only pay by the distance (even the rate of increment for distance is pretty generous within Seoul) and transferring to other bus or subway do not have extra cost (except very few subway or system run by different region). Arrival rates are also pretty good so make sure you use it a lot.

- **Transportation at night (taxi)**: That being said, you won’t need to use other transportation within Seoul unless you are moving very late at night. Lot of subways and buses stop working around 11pm~12am-ish. If you tend to stay far away from your home at night, you will have to use taxi. You can get a taxi either by catching them on the go or by app (sth like kakao taxi). Just be warned that it is bit harder to catch taxi at night as there are less supply.

## General travel places recommendation

- Official visitor guide: [LINK](https://english.visitseoul.net/)

- For full lists of places you can go, try out this [LINK](https://en.namu.wiki/w/%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C/%EA%B4%80%EA%B4%91)

## Brief personal recommendations

- Places around “seoul forest” are quite nice. The park is very nice with small pond and place near the park (Seongsu-dong) has sort of New York Brooklyn vibe(shameless comparison, I know…). Just be aware that there tends to be lot of people around.

- Try out places around the old city. These places are generally called “within four doors.” This is because in the past, the Seoul walled city had four main doors for entry. Unlike other places in Seoul which are now pretty modern, old city area still has lot of traditional places. Try out some traditional Korean house villages (like Bukchon Hanok Village and Seochon). I personally like area around Seochon. They are also close to the palaces so you will be able to visit them as well. Overall, area around the palaces (Seochon or Bukchon are all places surrounding the old palaces) are generally nice place to walk around. 

- Walking along the river is nice. Especially try out Cheong-gye-cheon stream at night. Having a night picnic near Han-gang river is also a nice experience. 

- If you like theme parks, be sure to try out **[Lotte World Adventure](https://adventure.lotteworld.com/eng/main/index.do)**. It used to be the biggest **In-door Theme park** until 2010. It is also known for having many *[dark rides](https://en.wikipedia.org/wiki/Dark_ride)*. It is also close to shopping mall (Lotte mall is right next to it) and **Lotte World Tower** which is currenlty the tallest building in Korea.[^1]

[^1]: It also holds few other records: (1) 8th tallest building in the world, (2) Tallest building out of all OECD countries.

- Try out some traditional markets: Places like Gwang-jang market or Tong-in market are very interesting places to go and eat some snack foods.

- If you have time, you could go to Sinchon which has university (Yonsei University) I am from. Although it is not as fancy as universities in Europe or US, it is overall clean and nice. Even though place is bit dying now, Sinchon is also known as one of the popular places for university students. You will be able to feel some freshman(?) vibe.[^2]

[^2]: Just be careful not to confuse **Sinchon** with **Sincheon**. The one I am referring to is located in the north of the river. On the other hand, Sincheon is located in the south.

- Although not my favorite, I guess you will probably be visiting Gangnam at least once when you are in Seoul. It is sort of like SOHO in UK. I do think it is a bit tourist-trap place but it does have some nice restaurants and places. 

- If you are a “park person”, try out Olympic park. It is also pretty close to Seok-chon lake which is also a famous place for a walk. But note that the place might be packed with people depending on when you go.

- Korea also has some nice coffee shops so try them. Good thing about cafes in Korea is that it is very convenient to work (e.g. using laptop). Lot of coffee shops in Korea have large tables and power outlets around.

## Personal food recommendations

- Korean BBQ: I think Korean BBQ is now quite popular even outside of Korea. Big advantage of eating Korean BBQ in Korea is that it is relatively cheaper. If you have time, try places like “ha-nam pig house”, “Go-ban sik-dang”, “byeok-je kalbi”, etc.

- Korean fried chicken: Korean fried chicken is very tasty. There are many places (e.g. BBQ chicken, BHC chicken, etc) you can get it from and they all have their own specialties. I recommend you get a take-out and eat it near Han-gang river with some beer.

- Cold noodles (e.g. Pyeong-yang Neng-myeon): Korea also has nice cold noodles. Peyong-yang Neng-myeon is my favorite but opinions are divided (some people don’t like it because it tastes quite bland). Try places like “ure-ok”, “bong-phee-yang”, “ul-ji-myeon-ok”, “ul-mil-dae”. Other than Pyeong-yang Neng-myeon, bean noodle is also a nice choice. It is basically noodle served in a soup made from grinding beans.

- Traditional Korean food: Unlike course style cuisine in other countries, interesting aspect about korean cuisine is that it is usually served all at once. So when you order some food, it will be served with other side dishes (usually called "ban-chan"). Also good thing about this side dishes is that you can ask a refill for these side dishes for free. Be sure you go to some traditional Korean food restaurant to check out these dishes.

