---
title: Misc.
toc: true
---

## Software

### Quarto

- Quarto working paper template for Economics: [\[github link\]](https://github.com/hchulkim/econ-paper-template/tree/main) [\[Blog post\]](https://hchulkim.github.io/posts/quarto-paper-template/)

### Scripts

- `Dockerfile` for empirical analysis (`R`, `Python`, `Julia` with dependency management setup): [\[link\]](https://hchulkim.github.io/posts/dockerfile-template/)

## Math

### (Partial) Solutions

- [Introduction to set theory (Hrbacek and Jech)](https://hchulkim.github.io/tools-site/teaching/set.html)
- [Real analysis (Folland)](https://hchulkim.github.io/tools-site/teaching/metrics.html)

## Courses

These are some info on the courses that I took or self-studied.

<details>
<summary><strong>List of courses</strong></summary>
- PhD Microeconomic Theory I (ECON 7100, UPenn, Fall 2024): [\[Personal summary\]](personal/econ6110.qmd)

- PhD Macroeconomic Theory I (ECON 7200, UPenn, Fall 2024): [Personal summary]

- PhD Econometrics I (ECON 7300, UPenn, Fall 2024): [Personal summary]

- PhD Game Theory and Applications (ECON 6110, UPenn, Spring 2025): [Personal summary]

- PhD Applied Econometrics (HCMG 9010, UPenn, Spring 2025): [Personal summary] 

- PhD Advanced Real Estate and Urban Economics (REAL 9470, UPenn, Spring 2025): [Personal summary] 

- PhD Cities in Developing Countries (REAL 9490, UPenn, Spring 2025): [Personal summary]

- PhD Public Economics (BEPP 9330, UPenn, Spring 2025): [Personal summary] 

- PhD Topics in Empirical Microeconomics: Spatial Economic Analysis (ECON 8400, UPenn, Spring 2025): [Personal summary]

</details>