---
title: "Short notes on papers"
description: "My personal notes on papers that I read"
date: "2026-04-21"
toc: true
categories:
  - study
---

# Notes

These are my personal notes on set of papers that I read for reference. Note that they are an overall summary of the papers. Rather, it is just a list of points that I want to remember about the paper.  

## Research general

- Mahoney (2022): Principles for Combining Descriptive and Model-Based Analysis in Applied Microeconomics Research.
  - From descriptive to model-based analysis: Motivate readers from descriptive (showing the variation you are leveraging); Let the descriptive guide your model.
- Berk, Harvey, and Hirshleifer (2017): How to write an effective referee report and improve the scientific review process.

## Topics: Trade

### Eaton and Kortum (2002, 2012): "Technology, geography, and trade", "Putting Ricardo to work"

- **Contribution and empirical limitation of the traditional Ricardian model:** It provides a foundational rationale for why trade occurs and characterizes the gains from trade regarding comparative advantage and productivity differences. However, this approach faces computational challenges: 1) it leads to discrete equilibrium types that are tedious to compute, and 2) tracking comparative advantage across multiple countries over multiple goods becomes empirically intractable.
- **Contribution and limitation of Dornbusch, Fischer, and Samuelson (1977):** This moves to a multiple-goods setting by employing a continuum of goods, which eliminates the discrete wedges in the equilibrium problem found in the traditional Ricardian model. It also introduces trade costs to rationalize the fact that countries tend to consume more domestically produced goods. However, this framework remains limited to a two-country setting.
- **Contribution of Eaton and Kortum (2002):** They incorporate productivity as realizations of random variables drawn from a Frechet distribution. Since this distribution is smooth, it solves the discrete wedge issues in the equilibrium. Furthermore, the model is highly tractable because we only need to track the distribution parameters and the statistics derived from them.
- Role of $A_i$: Governs absolute advantage (a higher value implies that the labor requirement is likely to be lower for any given good).
- Role of $\theta$: Governs comparative advantage (a higher value implies that the variability of the labor requirement is small).

### Dekle, Eaton, and Kortum (2007): "Unbalanced trade" 

- **Hat algebra**: Technique used in international trade for computing counterfactual change.
- Instead of solving a trade model for the full level of every variable (which requires knowing many hard-to-measure parameters), you can rewrite the model in relative changes. When you do this, lot of unobservable structural parameters cancel out. Thus, you're left with equations that relate the proportional changes you care about to things you can actually observe, like trade shares.
- The paper uses this method to compute counterfactual outcomes where trade in manufacture is fully balanced.

### Antras, Fort, and Tintelnot (2017): "The margins of global sourcing: Theory and evidence from US firms"

- Understanding the tension between intensive margin (sourcing potential through lower marginal cost) and extensive margin (heterogeneous country-specific fixed cost).

### Hsiao (2026): "Coordination and commitment in international climate action: Evidence from palm oil"

- This paper develops a dynamic empirical framework to quantify the impact of trade policy as a substitute for weak domestic environmental regulations. While such import tariffs can do an equivalent job of targeting emitters, the effect is dampened if coordination and commitment fall short.

### Anderson and van Wincoop (2003): "Gravity with gravitas: A solution to the border puzzle"

- Formalize the empirical gravity equation into structural gravity model.
- Mainly the structural gravity equation adds "multilateral resistance" term into the former empirical equation. This can be thought of as average trade barriers the region face with all of its trading partners.
- Thus, key implication of theoretical gravity equation is that trade between regions are determined by *relative* trade barriers. To be more specific, trade between two regions depend on the bilateral trade barrier between them relative to the average trade barriers each region faces with all of their trading partners.
- This leads to very interesting implications that seem to explain some of the puzzles that were found in previous trade literature. e.g. increased trade barrier affects multilateral resistance (price index) less for large economy as barrier is not imposed on within trade. Also, increased trade barrier will lead to more trade between small countries as relative trade barrier between them becomes lower due to higher increase in multilateral resistance.
- In some sense, multilateral resistance can be thought of as a "GE effect."

### Juanma Castro-Vincenzi (2026): "Climate hazards and resilience in the global car industry" 

- This paper investigates how climate change affects the spatial organization of multinational production (firms).
- Firms partially offset the output decline by ramping up production at other plants within their network. This is shown using a model that is developed to represent how firms determine their plant locations and capacities, conditional on weather-related disruption risk.
- Key challenge in the estimation is that the optimization problem is combinatorial. This is alleviated as the problem is convex with linear constraints. This allows the researcher to efficiently solve the problem in polynomial time. 
- In the counterfactual analysis, the paper shows that firms build additional smaller plants. These plants also maintain a larger spare capacity to buffer against weather-induced disruptions. 
- But firm's adaptation hurts consumer surplus as plant reconfiguration increases average prices due to productivity and capacity losses.

### Caliendo and Parro (2022): "Trade policy" (Handbook of International Economics, Volume 5)

- Kovak (2013) finds that regions exposed to the largest tariff declines experienced smaller wage growth relative to regions that experienced smaller tariff cuts.
- Important methodological contribution of Kovak (2013) is that it develops economic theory that justifies the use of shift-share design.
- One challenge is that shift-share is about "differential effect" and not about "aggregate effect"; Another issue is that there was not a straightforward economic model that justify the use of shift-share specification.
- We can use simple economic model to justify shift-share regression with assumption that each region is imperfectly mobile and is small open economy (each region is price taker).

## Transportation (trade)

### Donaldson (2018): "Railroads of the Raj: Estimating the impact of transportation infrastructure"

- While economic theory (trade) predicts that improvements in transportation infrastructure leads to increase in welfare, rigorous empirical understanding of such improvement's impact on lowering trade cost and its impact on welfare has not been fully studied.
- Using rich dataset on construction of colonial India's railroad network, the paper 1) estimates railroad's impact on trading environment through lowering trade cost between regions; 2) estimates railroad's effect on economic welfare; 3) specifies the general equilibrium trade model to relating the observed railroad-driven reduction in trade costs to the observed railroad-driven increase in welfare using sufficient statistic approach (This provides one economic mechanism behind such gains from railroads estimated from reduced-form result).

## Method: demand estimation

- This is on a separate [blog post](https://hchulkim.github.io/posts/demand-io/index.html).

## Method: Production function estimation

### Olley and Pakes (1996): "The dynamics of productivity in the telecommunications equipment industry"

- Proably the first paper that formalizes the proxy variable estimation method.
- Idea is using investment as a proxy for unobserved productivity. Under certain assumptions, we can invert this to apply control function to partial out the unobserved productivity shock from the estimation process.

### Levinsohn and Petrin (2003): "Estimating production functions using inputs to control for unobservables"

- This paper is more about solving a practical issue that comes up when employing OP method in data.
- Either due to data limitation or reality, there are many cases where investment is 0 for most firms. This means either the strict monotonicity assumption cannot be kept or we need to throw out these observations which seem arbitrary.
- LP propose one solution: use intermediate input (which are usually used consistently by firms) and apply similar assumptions.

### Ackerberg, Caves, and Frazer (2015): "Identification properties of recent production function estimators"

- ACF argues that (at least in principle) OP and LP's identification strategy suffers from functional dependence problem.
- In OP and LP's case, as labor and material is both flexible input, there is not additional variation left in labor that can be used to identify the coefficient on labor input in the first-stage of the estimation.
- Their proposed solution is to adjust the timing assumption of the labor input (from $t$ to $t-b$ period) and moving the identification of all the coefficients to second-stage of the estimation.

### Gandhi, Navarro, and Rivers (2020): "On the identification of gross output production functions"

- Focus on nonparametric identification of gross output production function estimation in the presence of both flexible and nonflexible inputs under the model structure of the proxy variable approach.
- The paper shows that at least for gross output production (where material input is in RHS of the equation), previous ACF still suffers from identification issue.
- Unless we have additional sources of exogenous variation (e.g. price), proxy variable structure does not suffice to identify the gross output production function.
- One solution posed by GNR is linking the FOC condition for the flexible input to the production function.
- However, note that this can be "somewhat" alleviated if we consider value-added function (material is not in the equation) or if we assume Leontieff production function (aka structural valude added). $Q = \min (\gamma M, F(L, K))$ and cost minimization gives $Q = \gamma M = F(L,K)$.

## Method: CDCP

### Solution 1: Moment inequality

#### Holmes (2010): "The diffusion of Wal-Mart and economics of density"

#### Dickstein and Morales (2018): "What do exporters know?"

### Solution 2: Squeezing algorithm

#### Panle Jia (2008): "What happens when Wal-Mart comes to town: An empirical analysis of the discount retailing industry"

- Estimating impact of large chain entry (e.g. Wal-Mart, Kmart) on small local retail stores.
- Key economic forces: competition effect and chain effect. The advantage of her model is that she can model relatively flexible competition patterns between retailers (between chains, chains and small stores) and also incorporates interdependence in chain's decision on market entry (store's profit depends on entry decisions in other markets).
- The benefit of her empirical model is that supermodularity structure of the game allows her to bound set of potential Nash equilibria. This is where the term "squeezing" comes from --- you can exploit the game's supermodularity to squeeze set of solutions.
- Empirical setting is very similar to Holmes (2010) --- but unlike Holmes, Panle has static model. Panle also employs squeezing algorithm which allows her to fully solve the model unlike Holmes (moment inequality does not fully solve the model). Holmes's model is dynamic single-agent setup --- he estimates economies of density and business stealing effect using Wal-Mart's dynamic expansion decisions. In Panle's paper, chain effect is similar to economies of density and is recovered using geographical concentration of Wal-Mart and Kmart stores. But she does not have business stealing effect because she needs to have supermodularity in the profit function to solve the model.
- Another limitation is that her algorithm only works for two agents making combinatorial decisions.

## Method: DDC

### Dynamic discrete choice problem using NFXP method

#### Rust (1987): "Optimal Replacement of GMC Bus Engines: An Empirical Model of Harold Zurcher"

- Reviewed Takamasa Otake's note which is based on Shum's notes.
- Also reviewed Conlon's lecture videos and notes.
- Key assumption seems to be **conditional independence**:
\begin{align}
p(x', \varepsilon' \mid x, \varepsilon, i) &= p(\varepsilon' \mid x', x, \varepsilon, i) \cdot p(x' \mid x, \varepsilon, i) \\
&= p(\varepsilon' \mid x') \cdot p(x' \mid x, i).
\end{align}
First factor indicates that $x'$ is sufficient statistics for $\varepsilon'$. Second factor indicates that once you condition on $x, i$, $\varepsilon$ does not hold any additional information about $x'$.
- Using expected value function for iteration instead of actual value function is also a nice trick. This is because value function is function of $\varepsilon$, making computation difficult. Using expected value function resolves this issue as it is indexed only by observed state and action.

### Dynamic discrete choice problem using CCP method

#### Hotz and Miller (1993); HMSS (1994); Aguirregabiria and Mira (2002)

## Method: Metrics

### Borusyak and Hull (2023): "Nonrandom exposure to exogenous shocks"

- The paper summarizes OVB that can arise when estimating causal effect of treatments/instruments that combine multiple sources of variation and develops method to alleviate it.
- The main reason OVB occurs is that such treatments/instruments combine variations, not all of which are exogenous. Treatment can have nonrandom (endogenous) exposure to exogenous shock which can bias the estimation.
- Example using transportation infrastructure improvement: Railroad construction itself can be plausibly exogenous to unobserved local characteristics. But urban regions will systematically receive higher growth in market access as they tend to be closer to the potential planned railroads. Then this correlates market growth induced from railroad construction to unobserved characteristics of urban regions that are also correlated with error terms.
- Solution is "recentered-IV" which basically purges OVB by netting out "expected shock" which can be constructed from specifying the shock assignment process.
- e.g. for railroads, you could permute the timing of railroads construction to create counterfactual railroads construction to net out the expected market growth from the actual realized market growth.
