baseURL: "https://hchulkim.github.io" 
title: Hyoungchul Kim
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: https://www.dropbox.com/scl/fi/k05ar0ig471kqpzw85z5b/cv-kim.pdf?rlkey=f33cey8fcjezo5c2w4g6thf45&dl=0
          weight: 1
        - name: Working Papers
          url: working/
          weight: 2
        - name: Publications
          url: papers/

params:
    description: "I am an incoming Ph.D. student in *Applied Economics* at the *Wharton School, University of Pennsylvania*."
    author: Hyoungchul Kim
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hyoungchul Kim
          subtitle: "I am an incoming Ph.D. student in Applied Economics at the Wharton School, University of Pennsylvania."
          imageUrl: personal.jpeg
          imageWidth: 160
          imageHeight: 160
          imageTitle: Hyoungchul Kim
          buttons:
            - name: CV
              url: https://www.dropbox.com/scl/fi/k05ar0ig471kqpzw85z5b/cv-kim.pdf?rlkey=f33cey8fcjezo5c2w4g6thf45&dl=0
            - name: Working Papers
              url: working/
            - name: Publications
              url: papers/
    socialIcons:
        - name: Email
          url: mailto:hchulkim@wharton.upenn.edu
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=GaRgVqoAAAAJ&hl=ko
        - name: GitHub
          url: https://github.com/hchulkim
        - name: Twitter
          url: https://twitter.com/hckim_econ

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hyoungchul Kim"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
