---
title: "Asahi-linux on Macbook Pro"
description: "My first experience with asahi-linux on Macbook Pro"
date: "2025-08-02"
toc: false
engine: knitr
categories:
  - software
---

## Background

If you have been following up my blog posts, you might have guessed that I am slowly transitioning to using Linux. It took a long 3-stage process to get me there. Windows, macOS, and Linux. It was mostly great, even though there were some small annoyances and hastles along the way (dependencies for installing some R packages, setting up Dropbox, etc). But there was another experiment I wanted to try out: **setting up Linux on my Macbook Pro (MBP)**. While I feel that MBP is just getting too overpriced (one of the reasons I started to transition to Linux in the first place), I still love the design and the build quality of the machine. So I decided to give it a try. But as you all know, setting up Linux on Mac is a painful and hardcore process. That's when I found out about [Asahi-linux](https://asahilinux.org/).

## Asahi-linux

Asahi-linux is a Linux distribution that is designed to run on Apple Silicon Macs. It is based on Fedora Linux.It is a community-driven project and is not officially supported by Apple.

Another good thing about Asahi-linux is that it is completely legal to use. It is not a hack or a jailbreak. Thus, you don't have to worry about getting your machine banned or your warranty voided. In fact, it is pretty easy to uninstall it so it shouldn't be much of an issue.

It is sort of similar to the good ol' bootcamp we used to have for Intel Macs for Linux. Basically we are setting up some partition on the disk to run Linux. 

## Caveats

While Asahi-linux is amazing, it is not without its caveats. Most of it is due to the fact that it is built upon macOS.Let me write down some of them as a warning to others.

- It is not officially supported by Apple. So you might not get the best support from Apple.
- Reverse engineering is not yet fully accomplished. Some features are not yet available (USB-C display, touchid, etc).
- It is not yet as stable as macOS. So you might encounter some issues.
- Currently, only M1 and M2 chips are supported. If you have an older machine or newer chips, it will not work.
- Due to ARM architecture, you cannot run x86_64 applications. So some softwares may not work in Asahi-linux.

## Setting up Asahi-linux

1. First, make sure your machine is compatible with Asahi-linux. You can check the [Asahi-linux website](https://asahilinux.org/fedora/#device-support) for the list of compatible machines.

2. Also make sure you have enough disk space. Asahi-linux is a bit larger than macOS. You need to have at least 100GB of free space.

3. Use the following command in terminal:

```{bash}
#| eval: false
curl https://alx.sh | sh
```

4. Follow the instructions in the terminal. It will guide you through the process of setting up Asahi-linux.[^1]

[^1]: It is very important to exactly follow the instructions in the terminal. If you don't, you might end up with a broken system. e.g. I struggled a bit on my first try because I did not hold the power button until "loading startup options..." appeared.

5. Your machine will reboot and you will see the option to boot into Asahi-linux.

6. If you need to boot into macOS, turn the power off and hold the power button until "loading startup options..." appears. Then select "macOS" and press enter.

7. You are all set!

## Current experience

For now, I am early in the game and trying out the power of Asahi-linux. I will probably use it as my additional machine along with my ThinkPad Ubuntu machine. I will update this section as I go along.

- Unlike Ubuntu, it is hard to install Dropbox. But fear not, there is a workaround. Try out [maestral](https://maestral.app/) instead. For some reason, Docker image installation option did not work for me but python version worked fine.